# Site settings
title: cornishmouth.cc
email: your@cornishmouth.cc
author: Aleksey Tarasov
description: "A blog about photography, life and travel"
url: "http://cornishmouth.cc" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
permalink: /:title
paginate: 5
excerpt_separator: <!--more-->
